# Site settings
title: Isabel Valladolid
description: 'Weblog'
url: ''
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Isabel Valladolid'
  email: isavalladolidd@icloud.com
  twitter_username: isavalladolidd  
  facebook_username: isabel.valladolidd
  github_username:  isavalladolidd
  linkedin_username:  isavalladolidd
  instagram_username: isavalladolid
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png','_site']
